I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 89, in script
    
Exception: Sayer 'Unfamilar' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 89, in script
    
  File "C:\Users\Jackson Wyndow\Downloads\renpy-6.18.3-sdk\renpy\ast.py", line 573, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Jackson Wyndow\Downloads\renpy-6.18.3-sdk\renpy\ast.py", line 491, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'Unfamilar' is not defined.

Windows-post2008Server-6.2.9200
Ren'Py 6.18.3.761
Grand Adventure Textless 0.0
